# Generated by Django 4.1.3 on 2022-11-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='country',
            new_name='location',
        ),
    ]
